#-*- coding:utf-8 -*-
{
    'name': 'College Base',
    'category': 'College Management System',
    'version': '13.0',
    'sequence': 1,
    'author': 'Training',
    'summary': 'Training',
    'description': "Training",
    'depends': ['mail','base'
    ],
    'demo':[],
    'data': [
        'security/college_security.xml',
        'security/ir.model.access.csv',
        'data/mail_template_data.xml',
        'data/sequences.xml',
        'wizard/wizard_student_remark.xml',
        'wizard/wizard_student_details_report.xml',
        'views/student_views.xml',
        'views/student_inherit_views.xml',
        'views/staff_views.xml',
        'views/res_users_view.xml',
        'views/report/student_details_template.xml',
        'views/report/report.xml',
        'views/menus.xml',
        'data/data.xml',
    ],
    'qweb':[],
    'images': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
